# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Platform Governance Research Lab"
title:              "Platform Governance Research Lab at Boston University"
description:        "The Platform Governance Research Lab is a research group focused on curbing disinformation through market solutions at Boston University."


# URL
url:                http://truthmarket.com
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "publications"
    href:           "/publication"
  - name:           "people"
    href:           "/people"
  - name:           "games"
    href:           "/games"
  - name:           "research"
    href:           "/research"
  # - name:           "blog"
  #   href:           "/blog"
#   - name:           "abstracts"
#     href:           "/abstracts"
  # - name:           "lab teachings"
  #   href:           "/presentations"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
