import React, { useState } from 'react';
import Layout from '@theme/Layout';
import styles from './publications.module.css';

/**
 * Publications page.
 *
 * Card-based layout (date | category | title | authors | abstract).
 * Sections: Papers (grouped by year), Talks, Slides, Press.
 *
 * The data lives in arrays at the bottom of this file. To add an entry
 * just append to the relevant array — fields are documented below.
 */

/* ------------------------------------------------------------------ */
/* Data                                                               */
/* ------------------------------------------------------------------ */

/**
 * Paper:
 *   { year, category, title, authors, abstract, links: [{label, url}] }
 *
 * Categories should map to a color in `categoryColor` below.
 */
const PAPERS = [
  {
    year: '2026',
    category: 'Working Paper',
    title: 'Market Design Interventions for Safer Agentic AI',
    authors:
      'Swapneel Mehta, Aaron Nichols, Abhishek Shah, Pratyay Banerjee, Nina Mazar, Marshall Van Alstyne',
    abstract:
      'We run an empirical study with human buyers purchasing products based on ads generated by large-language-model agents and find an increase in misleading advertising and consumer harm. Using our truth-warrant intervention we demonstrate how to curtail deception by dishonest agentic advertisers while improving the profits of honest ones.',
    links: [],
  },
  {
    year: '2024',
    category: 'Conference Paper',
    title:
      'Improving the Governance of Digital Platforms with Interactive Marketplace Experiments',
    authors:
      'Swapneel Mehta, Sverre Wiedswang, Zoey Yang, Nina Mazar, Marshall Van Alstyne',
    venue: 'International Conference on Computational Social Science (IC2S2)',
    abstract:
      'An empirical experiment presenting findings from the deployment of self-certification, or truth warrants, in a competitive two-sided e-commerce marketplace.',
    links: [
      {
        label: 'Slides',
        url: 'https://docs.google.com/presentation/d/1v_K9nGETVi-Vy8GKcllhJzeE_5_IspdDvK9JTvk6liY/edit',
      },
    ],
  },
  {
    year: '2024',
    category: 'Working Paper',
    title:
      'Truth is Warranted: The Impact of Self-Certification on Misinformation',
    authors:
      'Aaron D. Nichols, Nina Mazar, Tejovan Parker, Gordon Pennycook, David Rand, Marshall Van Alstyne',
    abstract:
      'Research on certifications and their utilization in the marketplace as an accountability mechanism for advertised claims.',
    links: [
      {
        label: 'PDF',
        url: 'https://www.dropbox.com/scl/fi/nopf4dhw86fh5oej7rquw/Certifiably_True-The_Impact_Of_Self_Certification_On_Misinfo.pdf?rlkey=vp9rcew7hq98plmhh5asofy93&dl=0',
      },
    ],
  },
  {
    year: '2024',
    category: 'Conference Paper',
    title: 'Secure Account Recovery for a Privacy-Preserving Web Service',
    authors: 'Ryan Little, Lucy Qin, Mayank Varia',
    venue: 'USENIX Security 2024',
    abstract:
      'A cryptographic protocol for secure account recovery in a privacy-preserving web service, using an oblivious pseudorandom function for email-based validation while preventing unauthorized access.',
    links: [
      {
        label: 'PDF',
        url: 'https://www.usenix.org/system/files/usenixsecurity24-little.pdf',
      },
    ],
  },
  {
    year: '2023',
    category: 'Op-Ed',
    title:
      'Improving §230, Preserving Democracy & Protecting Free Speech',
    authors: 'Marshall Van Alstyne, Michael D. Smith, Herbert Lin',
    venue: 'Communications of the ACM',
    abstract:
      'A framework for a decentralized market where no single party controls the flow of information.',
    links: [
      {
        label: 'Article',
        url: 'https://cacm.acm.org/opinion/improving-section-230-preserving-democracy-and-protecting-free-speech/',
      },
    ],
  },
  {
    year: '2023',
    category: 'Working Paper',
    title: 'Free Speech & the Fake News Problem',
    authors: 'Marshall W. Van Alstyne',
    abstract:
      'Examines the intersection of free speech and the rise of fabricated news stories, surveys regulatory solutions, and proposes new frameworks for addressing the issue in online media.',
    links: [
      {
        label: 'SSRN',
        url: 'https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4414261',
      },
    ],
  },
  {
    year: '2023',
    category: 'Working Paper',
    title:
      "Free Speech vs. Free Ride: Navigating the Supreme Court's Social Media Paradox",
    authors: 'Marshall W. Van Alstyne',
    abstract:
      'Examines the contradictory legal status of social-media platforms, which claim both publisher rights and common-carrier protections, and proposes a solution grounded in user choice and filter accountability. Uses marketplace and pollution analogies to argue for clearer regulation without government censorship.',
    links: [
      {
        label: 'PDF',
        url: 'https://truthmarket.com/papers/free_speech_vs_free_ride.pdf',
      },
    ],
  },
];

/**
 * Talk:
 *   { year, title, presenter, venues: string[] }
 */
const TALKS = [
  {
    year: '2024',
    title: 'Market Design Interventions for Safer Agentic AI',
    presenter: 'Aaron Nichols',
    venues: ['Yale AI/ML Conference', 'Columbia MarkTech Conference'],
  },
  {
    year: '2024',
    title: 'Improving the Governance of Online Marketplaces using Warrants',
    presenter: 'Swapneel Mehta',
    venues: ['Stanford Trust and Safety Research Conference'],
  },
  {
    year: '2024',
    title:
      'Certifiably True: The Impact of Self-Certification on Misinformation',
    presenter: 'Aaron Nichols',
    venues: [
      'Platform Strategy Research Symposium',
      'International Conference on Computational Social Science',
      'Freedom of Expression Scholars Conference',
    ],
  },
  {
    year: '2024',
    title:
      'Truth is Warranted: Addressing Misinformation in Information Markets',
    presenter: 'Marshall Van Alstyne',
    venues: ['Digital Platform Ecosystems Forum, University of Passau'],
    link: 'https://idw-online.de/en/news835047',
  },
  {
    year: '',
    title: 'Using Markets to Combat Misinformation',
    presenter: 'Marshall Van Alstyne',
    venues: ['Harvard University'],
    link: 'https://www.youtube.com/watch?v=G_UAuAdAgDQ',
  },
];

/**
 * Press:
 *   { year, title, author, publisher, url }
 */
const PRESS = [
  {
    year: '2023',
    title:
      'BU Professors Earn NSF Grant for Data Science Project Fighting Online Misinformation',
    author: 'Toni Fitzgerald',
    publisher: 'BU CDS',
    url: 'https://www.bu.edu/cds-faculty/2023/10/06/bu-professors-earn-nsf-grant-for-data-science-project-fighting-online-misinformation/',
  },
  {
    year: '2023',
    title:
      'BU Researchers Receive $550,000 Grant, Propose Holistic Approach to Misinformation',
    author: 'Anna Albrecht',
    publisher: 'The Daily Free Press',
    url: 'https://dailyfreepress.com/2023/10/25/bu-researchers-receive-550000-grant-propose-holistic-approach-to-misinformation/',
  },
  {
    year: '2021',
    title:
      "Now It's Harvard Business Review Getting Section 230 Very, Very Wrong",
    author: 'Mike Masnick',
    publisher: 'TechDirt',
    url: 'https://www.techdirt.com/2021/08/13/now-harvard-business-review-getting-section-230-very-very-wrong/',
  },
  {
    year: '2020',
    title:
      'How Your Company Can Fight the Never-Ending War Against Misinformation',
    author: 'Edward Segal',
    publisher: 'Forbes',
    url: 'https://www.forbes.com/sites/edwardsegal/2020/10/21/how-your-company-can-fight-the-never-ending-war-against-misinformation/',
  },
  {
    year: '2020',
    title: 'Platforms Forge New Paths',
    author: 'Peter Krass',
    publisher: 'MIT IDE (Medium)',
    url: 'https://medium.com/mit-initiative-on-the-digital-economy/platforms-forge-new-paths-c1e2f3541a8f',
  },
  {
    year: '2019',
    title: 'Could Taxes Deter the Spread of Harmful Fake News?',
    author: 'Anastasia Lennon',
    publisher: 'The Brink',
    url: 'https://www.bu.edu/articles/2019/deter-the-spread-of-harmful-fake-news/',
  },
];

/* ------------------------------------------------------------------ */
/* Style helpers                                                      */
/* ------------------------------------------------------------------ */

/**
 * Map of paper categories to a semantic color (matches site palette).
 * Add a new category here when introducing one.
 */
const categoryColor = {
  'Conference Paper': { bg: '#e6f1fa', fg: '#005286' },
  'Working Paper': { bg: '#f0eef6', fg: '#5b21b6' },
  'Op-Ed': { bg: '#fef3c7', fg: '#92400e' },
  Other: { bg: '#f3f4f6', fg: '#374151' },
};

function CategoryPill({ label }) {
  const c = categoryColor[label] ?? categoryColor.Other;
  return (
    <span
      className={styles.pill}
      style={{ backgroundColor: c.bg, color: c.fg }}
    >
      {label}
    </span>
  );
}

/* ------------------------------------------------------------------ */
/* Card components                                                    */
/* ------------------------------------------------------------------ */

function PaperCard({ paper }) {
  const [expanded, setExpanded] = useState(false);
  return (
    <article className={styles.card}>
      <div className={styles.cardMeta}>
        <span className={styles.year}>{paper.year}</span>
        <CategoryPill label={paper.category} />
      </div>
      <h3 className={styles.cardTitle}>{paper.title}</h3>
      <p className={styles.authors}>{paper.authors}</p>
      {paper.venue && <p className={styles.venue}>{paper.venue}</p>}
      {expanded && <p className={styles.abstract}>{paper.abstract}</p>}
      <div className={styles.cardActions}>
        <button
          type='button'
          className={styles.toggleButton}
          onClick={() => setExpanded((e) => !e)}
          aria-expanded={expanded}
        >
          {expanded ? '▾ Hide abstract' : '▸ Read abstract'}
        </button>
        {paper.links?.map((l) => (
          <a
            key={l.url}
            href={l.url}
            target='_blank'
            rel='noopener noreferrer'
            className={styles.linkButton}
          >
            {l.label} ↗
          </a>
        ))}
      </div>
    </article>
  );
}

function TalkCard({ talk }) {
  const Wrapper = talk.link ? 'a' : 'article';
  const wrapperProps = talk.link
    ? {
        href: talk.link,
        target: '_blank',
        rel: 'noopener noreferrer',
        className: `${styles.card} ${styles.cardLink}`,
      }
    : { className: styles.card };
  return (
    <Wrapper {...wrapperProps}>
      <div className={styles.cardMeta}>
        {talk.year && <span className={styles.year}>{talk.year}</span>}
        <span className={styles.muted}>Talk</span>
      </div>
      <h3 className={styles.cardTitle}>{talk.title}</h3>
      <p className={styles.authors}>Presented by {talk.presenter}</p>
      <ul className={styles.venueList}>
        {talk.venues.map((v) => (
          <li key={v}>{v}</li>
        ))}
      </ul>
    </Wrapper>
  );
}

function PressCard({ item }) {
  return (
    <a
      href={item.url}
      target='_blank'
      rel='noopener noreferrer'
      className={`${styles.card} ${styles.cardLink}`}
    >
      <div className={styles.cardMeta}>
        <span className={styles.year}>{item.year}</span>
        <span className={styles.muted}>{item.publisher}</span>
      </div>
      <h3 className={styles.cardTitle}>{item.title}</h3>
      <p className={styles.authors}>By {item.author}</p>
    </a>
  );
}

/* ------------------------------------------------------------------ */
/* Sections                                                           */
/* ------------------------------------------------------------------ */

function PapersSection() {
  // Group papers by year, newest first.
  const byYear = PAPERS.reduce((acc, p) => {
    (acc[p.year] ??= []).push(p);
    return acc;
  }, {});
  const years = Object.keys(byYear).sort((a, b) => b.localeCompare(a));

  return (
    <section className={styles.section} id='papers'>
      <header className={styles.sectionHeader}>
        <h2 className={styles.sectionTitle}>Papers</h2>
        <p className={styles.sectionDescription}>
          Peer-reviewed and working papers on marketplace design,
          self-certification, and agentic AI.
        </p>
      </header>
      {years.map((year) => (
        <div key={year} className={styles.yearGroup}>
          <h3 className={styles.yearLabel}>{year}</h3>
          <div className={styles.cardGrid}>
            {byYear[year].map((p) => (
              <PaperCard key={p.title} paper={p} />
            ))}
          </div>
        </div>
      ))}
    </section>
  );
}

function TalksSection() {
  return (
    <section className={styles.section} id='talks'>
      <header className={styles.sectionHeader}>
        <h2 className={styles.sectionTitle}>Talks</h2>
        <p className={styles.sectionDescription}>
          Selected invited talks and conference presentations.
        </p>
      </header>
      <div className={styles.cardGrid}>
        {TALKS.map((t) => (
          <TalkCard key={t.title + t.presenter} talk={t} />
        ))}
      </div>
    </section>
  );
}

function PressSection() {
  return (
    <section className={styles.section} id='press'>
      <header className={styles.sectionHeader}>
        <h2 className={styles.sectionTitle}>Press</h2>
        <p className={styles.sectionDescription}>
          Coverage of the lab's work in academic and general-audience outlets.
        </p>
      </header>
      <div className={styles.cardGrid}>
        {PRESS.map((p) => (
          <PressCard key={p.url} item={p} />
        ))}
      </div>
    </section>
  );
}

/* ------------------------------------------------------------------ */
/* Page                                                               */
/* ------------------------------------------------------------------ */

export default function Publications() {
  return (
    <Layout
      title='Publications'
      description='Papers, talks, and press from the Platform Governance Research Lab'
    >
      <main className={styles.page}>
        <header className={styles.pageHeader}>
          <h1 className={styles.pageTitle}>Publications</h1>
          <p className={styles.pageLede}>
            Research on marketplace mechanisms, truth warrants, and the
            governance of agentic AI marketplaces: peer-reviewed papers,
            invited talks, and selected press.
          </p>
          <nav className={styles.tableOfContents} aria-label='Sections'>
            {/* Plain <a> anchors — Docusaurus's static checker doesn't see
                section IDs on rendered components, but the in-browser scroll
                works correctly. */}
            <a href='#papers'>Papers</a>
            <a href='#talks'>Talks</a>
            <a href='#press'>Press</a>
          </nav>
        </header>

        <PapersSection />
        <TalksSection />
        <PressSection />
      </main>
    </Layout>
  );
}
